
@echo off

REM !!! Generated by the fmp-cli 1.86.0.  DO NOT EDIT!

md WingMenu\Assets\3rd\fmp-xtc-wingmenu

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-wingmenu-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\WingMenu\Assets\3rd\fmp-xtc-wingmenu\
